// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIPMJnFkH4OUKWLxq6H3iU0SLICHpY02g',
    appId: '1:812985698492:web:e14b3c2408cfd695b0a8b9',
    messagingSenderId: '812985698492',
    projectId: 'fluttercommerce-10cd6',
    authDomain: 'fluttercommerce-10cd6.firebaseapp.com',
    storageBucket: 'fluttercommerce-10cd6.firebasestorage.app',
    measurementId: 'G-E5GZZ42CPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0LZg1ERhAeDahKIbNnSB8NlNMw13wC0w',
    appId: '1:812985698492:android:6baa87d9fc188c2db0a8b9',
    messagingSenderId: '812985698492',
    projectId: 'fluttercommerce-10cd6',
    storageBucket: 'fluttercommerce-10cd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHYgY-MbypNLJTyySeRHaK3qrqst9Obcc',
    appId: '1:812985698492:ios:ccc1716340c4f82cb0a8b9',
    messagingSenderId: '812985698492',
    projectId: 'fluttercommerce-10cd6',
    storageBucket: 'fluttercommerce-10cd6.firebasestorage.app',
    iosBundleId: 'com.example.fluttercommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHYgY-MbypNLJTyySeRHaK3qrqst9Obcc',
    appId: '1:812985698492:ios:ccc1716340c4f82cb0a8b9',
    messagingSenderId: '812985698492',
    projectId: 'fluttercommerce-10cd6',
    storageBucket: 'fluttercommerce-10cd6.firebasestorage.app',
    iosBundleId: 'com.example.fluttercommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIPMJnFkH4OUKWLxq6H3iU0SLICHpY02g',
    appId: '1:812985698492:web:b90adaadf73cb6d7b0a8b9',
    messagingSenderId: '812985698492',
    projectId: 'fluttercommerce-10cd6',
    authDomain: 'fluttercommerce-10cd6.firebaseapp.com',
    storageBucket: 'fluttercommerce-10cd6.firebasestorage.app',
    measurementId: 'G-VD4F9KSH03',
  );
}
